import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import { Grid, Button } from '@mui/material';


export default function Home() {

  function pagamento() {
    console.log('PAGAMENTO');
  }

  function matricula() {
    console.log('MATRICULA');
  }

  return (
    <div className={styles.container}>
      <Head>
      <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />

      <h1 className={styles.title}>
          Welcome to <a href="https://www.wyden.com.br/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Wyden
          </a>
        </h1>
      </Head>

      <main className={styles.main}>
        <Grid container>
          <Grid item xs={12}>
            <Button onClick={matricula} variant="contained" href="/matricula">Matriculas
            </Button>
          </Grid>

          <Grid item xs={12} marginTop={1}>
            <Button onClick={pagamento} variant="contained" href="/pagamento">Pagamento</Button>
          </Grid>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>

  )
}